# Generated by Django 2.2 on 2019-04-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgeHandler.Key'),
        ),
    ]
