# Generated by Django 2.2 on 2019-04-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0002_auto_20190422_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicate',
            old_name='key',
            new_name='predicate',
        ),
    ]
