# Generated by Django 2.2 on 2019-04-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0004_auto_20190422_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicate',
            old_name='predicate',
            new_name='property',
        ),
    ]
