# Generated by Django 2.2 on 2019-04-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0005_auto_20190422_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='key',
            new_name='property',
        ),
    ]
