# Generated by Django 2.2 on 2019-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0006_auto_20190422_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
