# Generated by Django 2.2 on 2019-04-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0007_auto_20190423_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='keyword',
            field=models.CharField(blank=True, choices=[('b', '@base'), ('c', '@container'), ('x', '@context')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='key',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgeHandler.Context'),
        ),
    ]
