# Generated by Django 2.2 on 2019-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeHandler', '0008_auto_20190423_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='keyword',
        ),
        migrations.AddField(
            model_name='predicate',
            name='keyword',
            field=models.CharField(blank=True, choices=[('b', '@type'), ('i', '@id'), ('x', '@context')], max_length=2, null=True),
        ),
    ]
